spring:
  application:
    name: smallvote
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: resources:/**
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/templates/
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/vote?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    timeout: 10000
    expire: 180000
    database: 2
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.lf.entity
  configuration:
    map-underscore-to-camel-case: true
    # 开启详细的sql日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
